services:
  pgdatabase:
    image: postgres:16
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    networks:
      - pg-network
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./pgadmin_data:/var/lib/pgadmin:rw"
    ports:
      - "8080:80"
    networks:
      - pg-network

networks:
  pg-network:
    external: true

# I'm using VSCODE Extension *SQLTools* instead of pg-admin
